### ISSUE TITLE
Cannot login to the Tina Cloud.

### ISSUE THREAD

**Issue by youbaowangsheng** [tinacms/tina.io#1406]
Access is currently blocked.

Ensure that the Client ID environment variable matches the Client ID in your project settings on Tina Cloud.

Alternatively, ensure that you have access to edit this site. Have an admin check your access in the Tina Cloud dashboard.

I have add the environment variables and setup the project settings. But I can't login from the website.

**Comment by youbaowangsheng** [comment]
Does anyone encounter the same problem with me.

**Comment by kldavis4** [comment]
@youbaowangsheng would you mind jumping on our discord so we can better assist you there: https://discord.gg/U2M4r9HN ?
