### ISSUE TITLE
Framework-specific Guides

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tina.io#1437]
Now that Tina works with numerous frameworks, we should have pages for: "Tina + Remix", "Tina + Gatsby". These will outline any limitations with each Framework+Tina.

Each guide can detail constraints on X framework, such as:

- Will contextual editing work with X framework
- Will data-fetching work with X framework
- Is a redirect required to edit on /admin (rather than /admin/index.html)
- Which "assetsDir" should be used for X framework (for media, and for admin build directory)
- Links to starters/examples for X framework

**Comment by JS-GitRepo** [comment]
Just inserting my vote for Astro + Tina! It's something I've been dabbling with and can hopefully contribute to.

**Comment by danestves** [comment]
I can help with the "Tina + Remix" example, I'm building my site with Tina and Remix but using the express adapter, tell me if that works for you! :D

**Comment by jamespohalloran** [comment]
Took a first stab at some guides for the initial setup for each framework. 
https://github.com/tinacms/tina.io/pull/1496
V2 will probably be some deeper guides for each for handling things like data-fetching, visual editing, static vs SSR, etc for each framework.
