### ISSUE TITLE
Styles are not correctly applied to SVG in button

### ISSUE THREAD

**Issue by cameralibre** [tinacms/tina.io#1494]
I was just about to start the 'Getting Started' tutorial, and I _almost_ got nerd-sniped into fixing something on your website... lucky for me I don't understand Tailwind at all so I may have saved some time, but all you get is this lousy bug report :)

## Problem
When viewing [Getting Started](https://tina.io/docs/setup-overview/) in Firefox, the buttons are huge - both the buttons and their child SVG elements are filling 100% of their parent's width. (Tested on Mac & Linux)
When viewing the same page in Chromium, the buttons are the expected size but the SVG arrows are not visible, they have a size of 0×0. (Tested only on Linux)
## Fix
Put this... somewhere..? 🤷‍♂️️ to apply it to the SVG elements
```
margin-left: 1rem;
width: 1.625rem;
```

## Screenshots
<figure>
<img src="https://user-images.githubusercontent.com/15368010/219478367-6a04a174-4e63-4f56-bc5d-36db66583c60.png" alt="screenshot of SVG icons in firefox, showing both the problem and the fix"/>
<figcaption align="center"><em>Firefox: the first button has the fix applied, the second shows the oversized SVGs as currently visible on the site</em></figcaption>
</figure>

<figure>
<img src="https://user-images.githubusercontent.com/15368010/219478344-9950e2f0-b81e-48de-bbd5-60fa84f00018.png" alt="screenshot of SVG icons in chromium, showing both the problem and the fix"/>
<figcaption align="center"><em>Chromium: the first button has the fix applied, the second and third shows the missing SVGs as currently visible on the site</em></figcaption>
</figure>

**Comment by jamespohalloran** [comment]
Thanks for the report! Looks like the arrows have since been removed from the buttons:
<img width="823" alt="Screen Shot 2023-04-12 at 4 00 15 PM" src="https://user-images.githubusercontent.com/3323181/231558454-0ed61fa9-7a72-4ca8-b8ab-d3947a471984.png">
