### ISSUE TITLE
noindex dev/test site

### ISSUE THREAD

**Issue by lukethacoder** [tinacms/tina.io#1531]
It looks like google has indexed some ~~one~~ some of the vercel preview URLs 

- [https://tinacms-site-next-fs0oy2nni-tinacms.vercel.app/pricing/](https://tinacms-site-next-fs0oy2nni-tinacms.vercel.app/pricing/)
- [https://tinacms-site-next-git-pricing-page-tinacms.vercel.app/pricing/](https://tinacms-site-next-git-pricing-page-tinacms.vercel.app/pricing/)

probably not a good look having a pricing page visible with placeholder content and the lorem ipsum placeholder content. Not too sure how old this preview site is.

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/13529535/229660675-8091fc91-1f45-405c-be97-7e1f8ed83ac7.png">

<img width="710" alt="image" src="https://user-images.githubusercontent.com/13529535/229660704-919fb18a-531f-4f9f-b4ed-ee9ed38d0af1.png">

**Comment by lukethacoder** [comment]
<img width="546" alt="image" src="https://user-images.githubusercontent.com/13529535/229660917-8b5c3c70-f42a-4a94-a02c-060f0811899c.png">

**Comment by jamespohalloran** [comment]
Thanks for the heads up @lukethacoder. Fix deploying now!
