### ISSUE TITLE
Placeholder content on the Editorial Workflow page

### ISSUE THREAD

**Issue by infotexture** [tinacms/tina.io#1617]
Looks like this page was designed with _Lorem ipsum_ placeholders, but someone forgot to update the **Protect Branches** featurette before launch:

https://github.com/tinacms/tina.io/blob/8fb025325fa559b7e18741461c0e95d482243d4d/content/blocksPages/editorial-workflow.json#L37

🎗️ [Content-First](https://www.lukew.com/ff/entry.asp?915). [Death to Lorem Ipsum](https://www.lukew.com/ff/entry.asp?927).

**Comment by infotexture** [comment]
Looks like @scottgallant resolved this on Aug 3 with https://github.com/tinacms/tina.io/commit/d7331dafa1935518768abbaa47633f4c846e85c2 but forgot to close this issue.

**Comment by scottgallant** [comment]
Good catch, @infotexture
