### ISSUE TITLE
blank screen when logging into app.tina.io w/ email (specific account)

### ISSUE THREAD

**Issue by appinteractive** [tinacms/tina.io#1657]
Can't login to app.tinia.io, Firefox, Chrome (Brave), Safari, iOS, Wi-Fi and Mobile. I get the following error in the console, while the page (after login) shows only a forever spinner. Can't edit any of my client pages.

And yes, disabling any of my does not change anything.

<img width="803" alt="grafik" src="https://github.com/tinacms/tina.io/assets/432828/56d263eb-8c45-45f5-9b57-efa9ab92d966">

<img width="453" alt="grafik" src="https://github.com/tinacms/tina.io/assets/432828/1a7be609-7209-48ea-86de-288955c8eed3">

**Comment by appinteractive** [comment]
Seems that this ONLY happens on Email & Password login, Github login does work though.

**Comment by kldavis4** [comment]
@appinteractive sounds like a problem with your account. When did this start happening? Can you share the email account's email address? (Note that your github login and email login are _separate_ accounts in Tina Cloud)

**Comment by appinteractive** [comment]
@kldavis4 you are right... my account is broken, I'm not confident in sharing my email here though. How can I forward it to you? Thanks in advance.
