### ISSUE TITLE
Force Push button described in documentation is not there

### ISSUE THREAD

**Issue by ephemeral-ai** [tinacms/tina.io#1686]
There is a Force Push button described here: https://tina.io/docs/reference/content-api/data-layer/#conflicts

However, I don't see it in my tina.io dashboard.
<img width="471" alt="image" src="https://github.com/tinacms/tina.io/assets/48521874/bf64ea8c-836b-4939-b95a-4d2bc9f79b6b">

**Comment by kldavis4** [comment]
Thanks - docs are out of date. Force push is no longer an option.

**Comment by ephemeral-ai** [comment]
Thanks. 

For anyone else looking for the force push button (or trying to do what it might have promised):

You can force refresh the tina cms by changing the config file. I added an insignificant change (optional field) and it was able to force tina cloud to update and reflect the changes.
