### ISSUE TITLE
🐛 Bug - Link button in wysiwyg returns error

### ISSUE THREAD

**Issue by CodeSigils** [tinacms/tina.io#1705]
Rendering breaks when **insert link** button is pressed in wysiwyg editor. Returns "error occurred in `<Fk>`  and `<FormBuilder>` component".

- Note: This only happens when the link button is pressed in wysiwyg. The rendered md / mdx links are working fine. Everything else works fine.

- Confirmed in 4 recently updated browsers on  localhost 3000 on  a new machine.
- Confirmed also in next-tina barebones repo

- cli reports no errors:

![Screenshot from 2023-11-24 17-47-58](https://github.com/tinacms/tina-barebones-starter/assets/2639571/5789392e-dd88-40fc-be45-b710552fb690)

- Dev-tools are reporting the following :

![Screenshot from 2023-11-24 17-35-26](https://github.com/tinacms/tina-barebones-starter/assets/2639571/bfe0cde9-f8d4-4ca0-b247-5aaaaf9b37ad)

- When the link button is pressed, admin returns the following error in the gui:

![Screenshot from 2023-11-24 17-42-31](https://github.com/tinacms/tina-barebones-starter/assets/2639571/37d66227-05a5-49b4-9fe1-66898b402d75)

- Deployed on Netlify have the same problem

- nvm version: 0.39.5
- Node -v: v20.10.0 (lts iron)
- npm -v: 10.1.0
- OS: Ubuntu LTS

**Comment by maloua** [comment]
I've got the same issue, did you manage to solve this?

**Comment by CodeSigils** [comment]
I am closing this. Confirmed working with the following dependencies:

```json
"dependencies": {
    "@tinacms/auth": "^1.0.4",
    "dotenv": "^16.4.5",
    "next": "^14.2.3",
    "next-tinacms-cloudinary": "^5.0.3",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "tinacms": "^1.6.3",
    "@tinacms/cli": "^1.5.45",
  },
```
