### ISSUE TITLE
Unclear VDP

### ISSUE THREAD

**Issue by coderbm1** [tinacms/tina.io#1736]
Hello, here we can see Security contact https://tina.io/security/   but what are your processes? 

What is for example time to first reply / contact? (Like 'confirmation - received report' and similar)
How long researchers should wait to answer from your side?

Thank you
Kind regards

**Comment by scottgallant** [comment]
Hi @coderbm1, please reach out to [info@tina.io](mailto:info@tina.io) for more information regarding our SLAs and security processes.
