### ISSUE TITLE
🔍 GitHub | Investigate Old Environments

### ISSUE THREAD

**Issue by joshbermanssw** [tinacms/tina.io#1759]
### Context 
There are currently a bunch of environments in the GitHub project that have not been deployed in a few years even though Vercel is primary environment

- [x] Investigate, speak with Scott and see why they are there
- [x] Remove unnecessary environments

**Comment by Marxoz** [comment]
@scottgallant Can you please contact @joshbermanssw about this? We need to make sure that we are not deleting environments that are still in use

**Comment by isaaclombardssw** [comment]
@joshbermanssw could you link to the stuff we wanna ask about next time for reference for me? 

[This is the page we want to audit](https://github.com/tinacms/tina.io/deployments/Preview%20%E2%80%93%20tina-io)

**Comment by isaaclombardssw** [comment]
As per my chat with @jeffsee55, the environments with no recent deployments are most likely safe to remove.

**Comment by isaaclombardssw** [comment]
I probably won't get onto this – someone else will have to pick it up.

**Comment by joshbermanssw** [comment]
![Image](https://github.com/user-attachments/assets/040770be-9967-4159-8960-0cf35987f27c)

**Figure: Updated environments**
