### ISSUE TITLE
🔍 Tina.io Certificate Issue 

### ISSUE THREAD

**Issue by joshbermanssw** [tinacms/tina.io#1771]
From: @bradystroud 
Date: Thursday, 16 May 2024 at 9:28 am
To: @scottgallant, @bradystroud 
Cc: @adamcogan , @JackDevAU , @joshbermanssw 
Subject: Re: Tina.io - www.tina.io doesn't work

As per email thread, Re: Tina.io - www.tina.io doesn't work, visiting www.tina.io will prompt a connection not secure message indicating there are issues with the sites certificate 

_If struggling with replicating - try to use safari or firefox, or any search engine on your mobile phone_
 
![Screenshot 2024-05-17 at 9 19 40 am](https://github.com/tinacms/tina.io/assets/137844305/c600ebda-afa8-4c19-aa34-00d843149922)
**Figure: ❌ Error Message on Safari visiting www.tina.io**

**💼 Tasks**
- [ ] Investigate
- [ ] Fix
- [ ] Test

**✅ Acceptance Criteria**
- [ ] Users can access www.tina.io on safari without any error or warning messages.

**Comment by bradystroud** [comment]
Any update on this?

**Comment by kldavis4** [comment]
I think it is managed on Vercel. There may be a conflict between the redirect we have setup in route53 (www.tina.io -> tina.io) and vercel's cert. If you add the domain www.tina.io in vercel I think it will resolve the issue. (it doesn't seem like I am a member of the tina vercel org anymore)

**Comment by wicksipedia** [comment]
fixed by @chrisschultzssw
