### ISSUE TITLE
✨ Home page - improve features grid

### ISSUE THREAD

**Issue by sethdaily** [tinacms/tina.io#1790]
@joshbermanssw @bradystroud @landonmaxwell

As per our conversation,

- [x] Remove all the buttons on the cards – see #2
- [x] Make the whole card clickable – see links below for each one
- [x] Rollover – make the cards flip/change when hovered over (e.g. the card colour changes to highlight)
See example: https://codepen.io/elcan-kerimov/embed/EdMdXx?height=316&theme-id=0&default-tab=result
- [x] 4. Add 2 new cards with the content below
- [x] 5. Other page – give a suggestion for what to do with the cards on https://tina.io/enterprise/

**Visual Editing** (link to https://quick-edit-demo.vercel.app/admin#/~)
See content changes in real-time as you edit.

**Fully Open Source** (link to https://github.com/tinacms/tinacms)
Tina is licensed under Apache 2.0. It can be self-hosted or hosted on Tina Cloud.

**Develop Locally** (link to https://tina.io/ - it should scroll to the npx command at the top of the page)
Easily set up and run Tina locally to talk to your local filesystem.

**3rd-party Media** (link to https://tina.io/docs/reference/media/overview/)
Store Media assets in your repo or connect to S3, Cloudinary, DigitalOcean Spaces, etc. Or, use Tina Cloud (ADD LINK).

**Control your Components** (link to https://tina.io/docs/editing/blocks/)
Use pre-built templates or create custom components from scratch - you have full control to build your site how you want.

**Markdown at Scale** (link to https://tina.io/docs/editing/overview/ - to be replaced by a video)
Tina powers super-fast sites with 10,000+ pages using Markdown, the best language for your site content.

**Git Integration** (link to https://tina.io/editorial-workflow/)
Users can edit, save changes, and request approval from within the UI – while devs see the branches, commits, and pull requests in GitHub.

**Easy Documentation** (link to https://tina.io/docs/)
Tina’s docs run on TinaCMS – check it out!

![image](https://github.com/tinacms/tina.io/assets/130118701/9b77a9bd-48cb-4e40-a038-7ccdeb5620b8)
**Figure: make the changes here**

**Comment by sethdaily** [comment]
@joshbermanssw 
    > Make the whole card clickable – see links below for each one
You ticked this one but I don't think it's done - only the first box is clickable (and it goes to google.com)

**Comment by joshbermanssw** [comment]
Live and updated 
![Screenshot 2024-05-27 at 3 59 47 pm](https://github.com/tinacms/tina.io/assets/137844305/3ceed71e-0d62-4d3c-bcb2-0bc9df425bc4)
