### ISSUE TITLE
✨ Home page - blog post removing link text

### ISSUE THREAD

**Issue by landonmaxwell** [tinacms/tina.io#1798]
### 🩸 Pain
When a blog post has a url link in it, the link isn't showing up in the Recent Posts blog preview on the home page.
Instead it completely removes it, making sentences look incorrect.

### 💼 Tasks 

- [x] Stop the hyperlink from disappearing

### ✅ Acceptance Criteria 

- [x] Checked by William L & Landon

### 📸 Screenshots 

![image](https://github.com/tinacms/tina.io/assets/78135895/663ee9fb-bf9c-448f-b021-82b73c661047)

![image](https://github.com/tinacms/tina.io/assets/78135895/b204e447-f434-4bc6-84de-6bfe3145f230)

Cc: 
@william-liebenberg @sethdaily @wicksipedia

**Comment by joshbermanssw** [comment]
<img width="719" alt="Screenshot 2024-05-27 at 10 58 59 am" src="https://github.com/tinacms/tina.io/assets/137844305/d6ee1adb-7be4-414a-822a-70fc7dc40668">

**Figure: PR mentioned above, includes <a> text in blog posts**

**Comment by joshbermanssw** [comment]
<img width="719" alt="Screenshot 2024-05-27 at 10 58 59 am" src="https://github.com/tinacms/tina.io/assets/137844305/91741910-3ea7-4f9e-bdf5-579ef35d6b68">

**Figure: Fixed - request was only looking for 'text' text, not other types (i.e hyperlink)** 

✅Test pass with Landon
