### ISSUE TITLE
💸 Docs - enable live preview in editor

### ISSUE THREAD

**Issue by wicksipedia** [tinacms/tina.io#1812]
Currently the Tina docs does not use the live edit functionality of Tina. This makes it harder to edit the docs.

- [ ] Enable live previews

![Image](https://github.com/tinacms/tina.io/assets/600044/e9c18c92-1c5e-44c4-9897-142a36419f24)

**Comment by joshbermanssw** [comment]
Closing this - being addressed in https://github.com/tinacms/tina.io/issues/1941
