### ISSUE TITLE
💸 Tech debt - Upgrade packages

### ISSUE THREAD

**Issue by bradystroud** [tinacms/tina.io#1825]
Packages on tina.io are outdated

1. Update to latest versions

<img width="1083" alt="image" src="https://github.com/tinacms/tina.io/assets/38869720/ed16e8bd-8356-4964-98c3-03b485ff0773">

**Comment by Marxoz** [comment]
Best to wait for dependabot issues to be fixed | https://github.com/tinacms/tina-cloud/issues/2097
