### ISSUE TITLE
🐛  Newsletter modal - layout shift

### ISSUE THREAD

**Issue by bradystroud** [tinacms/tina.io#1829]
@joshbermanssw @bettybondoc

### 🐛 Describe the Bug
https://youtu.be/MP0jbtUHbGk

### 🧑‍💻 Reproduction Steps

1. Go to https://tina.io
2. Click on Subscribe
3. Fill out form
4. See layout shift

### 🎯 Expected Behaviour 
No layout shift

### 💼 Tasks
- [x] Fix

**Comment by joshbermanssw** [comment]
Fixed in https://github.com/tinacms/tina.io/pull/1881
