### ISSUE TITLE
✨  Menu - TinaCloud is confusing

### ISSUE THREAD

**Issue by piers-sinclair** [tinacms/tina.io#1831]
As per my conversation with @adamcogan @bradystroud and @camillars 

### 🩸 Pain

In the Tina menu system "TinaCloud" is confusing because I thought I would see info about the product.

### 💡 Suggested Solution

Change to "My TinaCloud"

### 💼 Tasks 

- [x] fix

### ✅ Acceptance Criteria 

"TinaCloud" menu option is changed to "My TinaCloud"

### 📸 Screenshots 

![image](https://github.com/tinacms/tina.io/assets/79821522/cb8c2582-f7f8-4546-9c98-7aa165a13c16)
**Figure: change this to My TinaCloud**

Cc:

**Comment by joshbermanssw** [comment]
Done
