### ISSUE TITLE
🤖 Vercel - Deployment Errors

### ISSUE THREAD

**Issue by joshbermanssw** [tinacms/tina.io#1846]
cc: @JackDevAU @bradystroud 

As per my conversation with @landonmaxwell there is an issue with all vercel deployments - getting 

`A Serverless Function has exceeded the unzipped maximum size of 250 MB.`

The current fix to this is to redeploy (select redeploy in vercel) all failed deployments and DO NOT select `Use existing Build Cache` and it will run

- [x] Investigate
- [x] Fix

**Comment by bradystroud** [comment]
@joshbermanssw this should be number 1 priority

**Comment by joshbermanssw** [comment]
✅ fixed - required environment variable being created in vercel
