### ISSUE TITLE
🐛  Dropdown menu under page title & unselectable

### ISSUE THREAD

**Issue by landonmaxwell** [tinacms/tina.io#1849]
### 🐛 Describe the Bug

On https://tina.io/ subdirectories, the dropdown menu is not selectable, and also appears underneath the page
E.g. https://tina.io/documentation/

### 🧑‍💻 Reproduction Steps

1. Go to ['tina.io/documentation'](https://tina.io/documentation/)
2. Hover over the dropdown menu and try to select an option 
3. See error 

### 💼 Tasks

- [ ] Fix overlay so menu is over the titles
- [ ] Fix so menu options can be selected

### ✅ Acceptance Criteria 

Checked by Landon

### 📸 Screenshots 

![image](https://github.com/tinacms/tina.io/assets/78135895/b599d149-e779-4cd5-9d9d-636645a288c1)

Cc: @camillars @sethdaily @joshbermanssw

**Comment by bradystroud** [comment]
Done - I just had to revert Joshes changes from #1847 
Sorry @joshbermanssw
