### ISSUE TITLE
✨ Google - Verify data consent settings (tina.io)

### ISSUE THREAD

**Issue by tiagov8** [tinacms/tina.io#1852]
**Is your feature request related to a problem? Please describe.**

As per @camillars, 

We need to set up consent mode on our website (tina.io) so we can receive consented data from end users in the European Economic Area (EEA) for advertising purposes.

**Describe the solution you'd like**

https://developers.google.com/tag-platform/security/guides/consent?consentmode=advanced#gtag.js_1

**Additional context**

I've used the [google@ssw.com.au](mailto:google@ssw.com.au) account to set this up via  **cookiebot.com** on **ssw.fr** (more details on Keeper)

https://admin.cookiebot.com/

It's currently on a Premium Trial for 14 days. We might want to pay and use it on other domains we have. E.g. SSW.com.au: https://github.com/SSWConsulting/SSW.Website/issues/2747

**Comment by joshbermanssw** [comment]
Fixed and live 

GDPR (EU) compliance sees that users are granted ability to modify at a granular level, which of their data is being tracked. 

as per https://github.com/tinacms/tina.io/issues/1852 I have implemented in a consent banner which omits a consent cookie based on the users choice.

- [ ] Test passed by Betty (UI) 
- [ ] Tested functionality of cookie with google tag manager preview mode 

<img width="1511" alt="Screenshot 2024-07-03 at 2 59 22 PM" src="https://github.com/tinacms/tina.io/assets/137844305/97c8fb17-ff44-42b7-be42-bb7e7395c34c">

**Figure: 💄 Consent Banner**

<img width="619" alt="Screenshot 2024-07-03 at 2 59 29 PM" src="https://github.com/tinacms/tina.io/assets/137844305/03eb523d-2233-4112-8a5e-83cd1fbc7943">

**Figure: 💄 Customisable Preferences Modal**

<img width="1170" alt="Screenshot 2024-07-03 at 2 59 55 PM" src="https://github.com/tinacms/tina.io/assets/137844305/95ad638a-87c3-430a-9661-54aa5f943f9c">

**Figure: 🍪Cookie sent correctly, shows that we can alter preferences**

![Screenshot 2024-07-03 at 3 04 28 PM](https://github.com/tinacms/tina.io/assets/137844305/20ecc0e2-5275-4699-bf4c-2ea9cc902c01)

**Figure: ✅GTM Correctly showing default declined preferences as per GDPR**

![Screenshot 2024-07-03 at 3 05 36 PM](https://github.com/tinacms/tina.io/assets/137844305/81c956b1-73a8-41c5-bda6-4ca57476d4a6)

**Figure: ✅After clicking 'decline all' we get updated consent as denied on ALL**

![Screenshot 2024-07-03 at 3 06 16 PM](https://github.com/tinacms/tina.io/assets/137844305/ec631021-c6dc-4f48-8685-8f95d4bd9d49)

**Figure: ✅ Tag blocked by Consent Settings (declined all)**
