### ISSUE TITLE
💄 Pricing page - line up the panels

### ISSUE THREAD

**Issue by sethdaily** [tinacms/tina.io#1870]
### 🩸 Pain
https://tina.io/pricing/
I see the free tier, then I have to scroll down to see the other ones, and the column is 3x as wide
Makes for a weird experience...I should be able to compare them side by side.

### 💡 Suggested Solution

Change from:

&nbsp;&nbsp;&nbsp;&nbsp;    ⬜
⬜⬜⬜

to

⬜⬜⬜⬜

### 💼 Tasks 

- [ ] Update the code
- [ ] Get the staging site checked by Landon

### 📸 Screenshots 
![image](https://github.com/tinacms/tina.io/assets/130118701/e8333deb-b92c-41f0-bac5-f0cf9e4ce698)
Figure: i have to zoom so far out to understand it 🤮 

Cc: @landonmaxwell

**Comment by joshbermanssw** [comment]
✅ Done

![Screenshot 2024-07-17 at 9 50 59 AM](https://github.com/user-attachments/assets/4572bc62-ce9f-41a7-906f-6835b7c12f45)
**Figure: 💄 Pricing Page**
