### ISSUE TITLE
💄 Not ready - move events block

### ISSUE THREAD

**Issue by sethdaily** [tinacms/tina.io#1885]
(reviewed by Brady for readability)
NOT READY

As per my conversation with Gert, Brady, Wicksy, and Josh, we voted against doing this because they think the events block is important to people.

For the record, I don't understand the reasoning and think that home page space is much better used by information about the product.

### 🩸 Pain
When landing on the home page:

- If I'm considering using Tina, the first thing I see when I scroll down is the 'Where Is Tina Going?' block. Doesn't answer any of my questions or show me why I should use Tina.
- If I don't know what Tina is and I stumbles upon the page, I'll see the 'Where Is Tina Going?' block and I won't learn anything about Tina, and I'll leave immediately.

### 💡 Suggested Solution
Move this block to the bottom of the page.

### 📸 Screenshots 
![image](https://github.com/tinacms/tina.io/assets/130118701/c32f5424-0f2b-4968-b3c3-c581e73ad0a0)
Figure: I would love for this space to show me the greatness of the product.

Cc:  @adamcogan @wicksipedia @Marxoz @landonmaxwell @bradystroud

**Comment by bettybondoc** [comment]
Cc: @adamcogan @wicksipedia @Marxoz @landonmaxwell @bradystroud @sethdaily

+1

The events block could live a bit further down. My recommended flow would be:

1. Hero
2. Trusted By
3. Key Features
4. Tina vs Competitors
5. CTA - Talk to an Expert
6. _**Events**_
7. Testimonials
8. Blog

This way, I get to know Tina, talk to someone, then see the community aspect (events, testimonials, blogs) to further reinforce my decision to engage with Tina.

**Comment by Marxoz** [comment]
@joshbermanssw please move it to just below the Talk to an Export Josh guy thingy

**Comment by joshbermanssw** [comment]
done and live ✅
