### ISSUE TITLE
Docs - Pagination buttons aren't being displayed correctly

### ISSUE THREAD

**Issue by JackDevAU** [tinacms/tina.io#1904]
CC @bradystroud @joshbermanssw 

Hey Team, 

### 🐛 Describe the Bug

The docs pagination buttons seemed to have broken recently and now the next button sits on the far left and the previous button has disappeared! 

### 🧑‍💻 Reproduction Steps

1. Go to https://tina.io/docs/schema/
2. Scroll down to the bottom
3. See error 

### 🎯 Expected Behaviour 

Both the Next and Previous buttons are visible and take up the full space

### 💼 Tasks

- [ ] Investigate and fix

### 📸 Screenshots 

![image](https://github.com/user-attachments/assets/5595ac37-ccc7-4016-ab67-4fcad27edccb)
**Figure: No Previous button! buttons seemed to be pushed to the left**

**Comment by joshbermanssw** [comment]
Closing this. As per our conversation @JackDevAU i have created a new PBI with the desired outcome. https://github.com/tinacms/tina.io/issues/1916
