### ISSUE TITLE
📕 ReadME - Tina.io GitHub 

### ISSUE THREAD

**Issue by joshbermanssw** [tinacms/tina.io#1928]
cc: @bradystroud 

With changes to how we login to Vercel - we need to ensure users who join the team can properly access all Tina records. 

🎯 **Expected Solution**
Backing off of last weeks CTF about ReadME's - lets re-work the Tina.io ReadME, including information of how a user can set up and work on tina.io locally. 

- [x] Include information on how users can set up tina CMS (and anything that is in a privated repository)

**Comment by isaaclombardssw** [comment]
This expanded a little off the original brief, after chatting to @bradystroud and @Marxoz we've decided to add the definition of done / other documentation in PR #2247.
