### ISSUE TITLE
📃 Docs - promote repo based media

### ISSUE THREAD

**Issue by wicksipedia** [tinacms/tina.io#1946]
As per my conversation with @adamcogan and @GordonBeeming 

We have a great feature with repo based media but it is hard to discover that on the website

- [x] Website - feature comparison - add repo based media
- [x] Website - feature squares - change from `3rd-party Media` to `Repo based media` since this aligns with the "own your content strategy"
- [x] Docs - on https://tina.io/docs/reference/media/overview/ explain what repo based media means and why this may be better than 3rd party providers
- [x] Docs - move `docs/reference/media` to `/docs`
~- [ ] Docs - move `Media` from `Reference` to `Core Concepts`~

![Image](https://github.com/user-attachments/assets/53cc3f04-1854-413b-8e3a-8ed5d3eb27ee)
**Figure: invert the feature so that you know you can serve media from TinaCloud + you still own it.... but can use others if you want to**

![Image](https://github.com/user-attachments/assets/5b79de3c-137f-48b5-8ae2-353caba31bf1)
**Figure: repo based media should be a product differentiator and should be promoted as such**

![Image](https://github.com/user-attachments/assets/2bcb2196-353f-4df3-85d2-247b33330bc4)
**Figure: move media so it isn't buried**

**Comment by Marxoz** [comment]
Approved - Happy to go ahead with the changes

**Comment by isaaclombardssw** [comment]
In review – also I spent some time on the comparison component, which had some serious issues need refactor (limited number of points of comparison and assigning to companies is super messy)
