### ISSUE TITLE
💸 Tech Debt - consolidate redirects approach

### ISSUE THREAD

**Issue by bradystroud** [tinacms/tina.io#1957]
There are a bunch of redirects in `now.json` (should change to `vercel.json`)
https://vercel.com/docs/errors/error-list#conflicting-configuration-files 

https://github.com/tinacms/tina.io/blob/700f41e80329930c41cc1829f1ff955ad7c62df0/now.json#L17-L26

There are also redirects in `next.config.js`

https://github.com/tinacms/tina.io/blob/700f41e80329930c41cc1829f1ff955ad7c62df0/next.config.js#L47-L53

- [ ] Put all redirects in one place

**Comment by joshbermanssw** [comment]
✅ Done and Live
