### ISSUE TITLE
💸 Tech Debt - Docs Navigation menu is not in tina

### ISSUE THREAD

**Issue by bradystroud** [tinacms/tina.io#1958]
Right now you have to edit a json file to edit the docs nav menu (ToC). It should be in Tina like everything else.

To save constantly maintaining this menu, consider generating it based on the file structure

- [ ] Move to a tina file
- [ ] or generate

https://github.com/tinacms/tina.io/blob/975e38787a045bc0a102cd796a46b795f30e8927/content/toc-doc.json#L1

**Comment by bradystroud** [comment]
The more I use the docs, I think the ToC should be generated based on the files and folders in the docs folder.
This would remove any maintenance debt and means every page will be in the ToC.

Downside is you cannot move files around in TinaCMS 😞

**Comment by joshbermanssw** [comment]
Closed - the docs navigation has been fixed by @isaaclombardssw
