### ISSUE TITLE
♻️ Refactor / Reimplement unsupported MDX components. 

### ISSUE THREAD

**Issue by joshbermanssw** [tinacms/tina.io#1967]
cc: @wicksipedia @JackDevAU @Jord-Gui 

As per my conversation with Matt, Jack and Jord, there are some features of TinaCMS that are not currently supported with our initial docs design. Such examples are with minimize text components. We have these components created but they are not supported to have code blocks, within a rich-text field, within a main rich text field. 

When this is supported.

- [ ] Reimplement MinimizeTab MDX component on all Docs/schema/refernce/field-types/* file examples. 
- [ ] Reimplement ImageAndText MDX Component on docs/extending-tina/custom-field-components/ and all Docs/schema/refernce/field-types/*

**Comment by Marxoz** [comment]
TinaCMS team needs to fix issues first
