### ISSUE TITLE
🐛  Doc Side-Menu – Missing Menu Highlights 

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tina.io#1970]
### 🐛 Describe the Bug
Some of the doc pages aren't being highlighted in the sidebar when on that page.

### 🧑‍💻 Reproduction Steps

1. Go to ['this link'](https://tina.io/docs/frameworks/remix/)
2. If it doesn't automatically open up, in the side menu open up the submenu's under 'Introduction | Getting Started | Framework-Specific Guides'.
3. See error.

### 🎯 Expected Behaviour 
Current page should be highlighted in the menu.

### 📸 Screenshots 
![2024-07-23_10-21-57](https://github.com/user-attachments/assets/790fd7b4-99b7-4020-aff3-aba874e30b0e)
**Figure 1 – expected menu highlight when on a matching page**

![2024-07-23_10-23-01](https://github.com/user-attachments/assets/fbd185dc-1eb4-4cc9-9c43-d925af8c4ecf)
**Figure 2 – highlight missing from some pages**

**Comment by joshbermanssw** [comment]
Cannot replicate anymore - i believe the toc-doc changes fixed this 👍 @isaaclombardssw
