### ISSUE TITLE
📝 Docs – Navigation – Bottom Navigation Missing

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tina.io#1971]
Links: https://tina.io/docs/reference/types/object/ and https://tina.io/docs/reference/self-hosted/tina-backend/netlify-functions/ 

- [x] Add navigation on the object page with previous page being https://tina.io/docs/reference/types/reference/ and the next page as https://tina.io/docs/reference/types/rich-text/
- [x] Add navigation to the [netlify page](https://tina.io/docs/reference/self-hosted/tina-backend/netlify-functions/) from https://tina.io/docs/reference/self-hosted/tina-backend/vercel-functions/ to https://tina.io/docs/reference/self-hosted/git-provider/overview/.

This is as per the document order in the side menu.

**Comment by joshbermanssw** [comment]
Done and live
