### ISSUE TITLE
🐛 Docs – Side-Menu does not expand as expected in some cases

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tina.io#1974]
### 🐛 Describe the Bug
The side menu does not automatically expand to show where the current page is for some pages accessed via search or direct link.

### 🧑‍💻 Reproduction Steps

1. Go to to [the tina docs](https://tina.io/docs/)
2. Click on the search bar, type in string.
3. Go to the [string page](https://tina.io/docs/reference/types/string/) via the search bar.
4. Side menu will not automatically expand to show the current page.

### 🎯 Expected Behaviour 
The side menu will expand to show the currently viewed doc page when accessed via the searchbar.

### ➕ More Information
Is this a new feature and not a bug?

**Comment by joshbermanssw** [comment]
@isaaclombardssw  i think this works now?

**Comment by isaaclombardssw** [comment]
Yep this should have been fixed since moving the docs table of contents into Tina.
