### ISSUE TITLE
💸 Tina Docs - Remove toc-doc.json

### ISSUE THREAD

**Issue by joshbermanssw** [tinacms/tina.io#1982]
cc: @bradystroud 

A large part of the Tina docs navigation component (left hand side of docs) is hard coded. Using information from `toc-doc.json` requires another component that needs to be maintained constantly. Also when we add new docs or guides or what-not users need to manually update this. 

We want to make this automatic

- [x] ~using the breadcrumbs from the getAllDocs() gql query we need a way to create a docsNav variable~
- [x] extend schema to include model of the docs toc
- [x] port data from old `toc-doc.json` to the new Tina JSON file
- [x] change generation logic to use the new tina implementation
- [x] Delete `toc-doc.json`  
- [x] Ensure pagination of docs matches docs navigation 

## Acceptance Critera

- Removed all usages of `old` stuff

**Comment by isaaclombardssw** [comment]
We're no longer approaching this using breadcrumbs to generate the table of contents, as per discussions with Brady we're going to add the docs TOC onto the Tina schema and maintain / generate it from there instead.

**Comment by isaaclombardssw** [comment]
This has been completed, the docs can now be set via Tina collections.
