### ISSUE TITLE
📃Fix broken link of documentation

### ISSUE THREAD

**Issue by KristenHu** [tinacms/tina.io#1985]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

This broken link in the ["Using Multiple Branches"](https://tina.io/docs/tina-cloud/branching/) page needs to be fixed.

![Image](https://github.com/user-attachments/assets/fe6db133-b6e5-44b8-b1ed-de7dbe2e701e)

### Reproduction

https://tina.io/docs/tina-cloud/branching/

### System Info

Browsers: Chrome

### Validations

- [x] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [docs](https://tina.io/docs).
- [x] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by wicksipedia** [comment]
unable to reproduce

**Comment by piers-sinclair** [comment]
I am having this issue on my machine as well


![Image](https://github.com/user-attachments/assets/99f036af-7e85-4b2f-b1e8-17b07094e77c)

**Figure: A gif of the problem**

**Comment by wicksipedia** [comment]
ok, looks like the repo is private and that is why the link isn't working for you

**Comment by ncn-ssw** [comment]
@wicksipedia @piers-sinclair 

The link is broken as the repository at https://github.com/tinacms/demo-incremental/tree/main is private.

**Comment by wicksipedia** [comment]
Repo has been made public - link should now work
