### ISSUE TITLE
📝 Docs Improvements – "Using the Tina Editor" page

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tina.io#2000]
### Pain

Currently there's some text that's missing what I suspect is an image, or other context that makes it fit in the doc content.

### Task

- [ ] Add an image of a Tina editor folder.

### Screenshot

![Image](https://github.com/user-attachments/assets/f77bb54e-f805-49e2-8bf0-bbf51733bb3e)

**Comment by joshbermanssw** [comment]
✅Done and live - removed out of context text.
