### ISSUE TITLE
🐛 Contribution Doc Pages – Ambiguous Wording

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tina.io#2004]
### 🐛 Describe the Bug
Wording change on the below pages:

- https://tina.io/docs/contributing/setting-up/
- https://tina.io/docs/contributing/troubleshooting/
- https://tina.io/docs/contributing/releasing/
- https://tina.io/docs/contributing/guidelines/

### 🧑‍💻 Reproduction Steps + 🎯 Expected Behaviour 
Go to the above warning callout – it mentions the docs are out of date where it should say the page is out of date.

### 💼 Tasks
- [x] Change "These docs are out of date" to "This page is out of date" in the callout.

**Comment by joshbermanssw** [comment]
Is this done? @isaaclombardssw

**Comment by isaaclombardssw** [comment]
Yep this was done a week or two ago - closed.
