### ISSUE TITLE
🐛 Docs – Broken Links in certain Tables of Contents

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tina.io#2012]
### 🐛 Describe the Bug
Some pages, the right hand side table of contents links don't match the heading Ids.

ex. https://tina.io/docs/editing/blocks/

### 🧑‍💻 Reproduction Steps

1. Go to ['this page'](https://tina.io/docs/editing/blocks/)
2. Click on 'Adding a visual block selector (Experimental)' on the RHS table of contents
3. See error 

### 🎯 Expected Behaviour 
Should link to the 'Adding a visual block selector (Experimental)' heading in the document.

### 💼 Tasks

- [ ] Investigate and fix.

### ✅ Acceptance Criteria 
- [ ] All doc page tables of contents have been checked for faulty links.

### 📸 Screenshots 
![Image](https://github.com/user-attachments/assets/c1661fb9-280c-4a91-acf0-4a6cbd8da6c3)
**Figure – showing the different between the table of contents link + href, and the title Id**

**Comment by joshbermanssw** [comment]
I looked at this briefly with another PBI i was working on, its because of the way that the components variable creates the id's for headers with non alphanumeric chars and how the ToC generates and looks for IDs

**Comment by tiagov8** [comment]
Related duplicated (therefore closed) Issue: https://github.com/tinacms/tina.io/issues/2032

**Comment by joshbermanssw** [comment]
double whammy, fixed in pr #2139
