### ISSUE TITLE
✨ New pricing page

### ISSUE THREAD

**Issue by bradystroud** [tinacms/tina.io#2030]
cc @wicksipedia @Levijj22 @bettybondoc

![Image](https://github.com/user-attachments/assets/c03993ba-73a4-4672-a4ea-1e161a400a47)

**Comment by bettybondoc** [comment]
cc @bradystroud @landonmaxwell @joshbermanssw 

As per email thread **Re: 🦙Tina - Pricing Tiers to be more competitive**

Please see updated prototype
[Prototype – Tina.io Pricing E – Web V2](https://www.figma.com/proto/Jyj0SszjfSBc6Minkl3g1l/Tina.io?node-id=865-2126&t=eYZzJhaLpC7GkK7C-0&scaling=scale-down-width&content-scaling=fixed&page-id=673%3A2513&starting-point-node-id=865%3A2126)
[Prototype – Tina.io Pricing E – Mobile](https://www.figma.com/proto/Jyj0SszjfSBc6Minkl3g1l/Tina.io?node-id=879-3098&t=eYZzJhaLpC7GkK7C-0&scaling=scale-down-width&content-scaling=fixed&page-id=673%3A2513&starting-point-node-id=879%3A3098)

![Image](https://github.com/user-attachments/assets/bb5cbb1f-6d6f-49f8-a48b-8d5a8883b8bd)

Figure: Pricing E – V2

**Comment by manideep1428** [comment]
Hello , can I do this?

**Comment by manideep1428** [comment]
saimanideep.ch12345@gmail.com

**Comment by joshbermanssw** [comment]
Pricing Page is live :) 

![Image](https://github.com/user-attachments/assets/0ffccb0a-09fb-4948-80cb-708b92cded8f)

**Figure: Live pricing page on tina.io**
