### ISSUE TITLE
🐛 Tina Docs - Bug on anchor links for headings that have symbols

### ISSUE THREAD

**Issue by tiagov8** [tinacms/tina.io#2032]
### 🐛 Describe the Bug

Anchor links (Table of Contents sidebar) won't work with symbols

E.g. On this page https://tina.io/docs/using-tina-editor/ there is a section called "What's Next?" Both apostrophe and question mark are converted to a dash...

So the link is
https://tina.io/docs/using-tina-editor/#what-s-next-
and dosn't work ❌

The correct link should be
https://tina.io/docs/using-tina-editor/#whats-next

### 💼 Tasks

- [ ] 1. Investigate and fix

**Comment by isaaclombardssw** [comment]
Same issue as PBI https://github.com/tinacms/tina.io/issues/2012

**Comment by bradystroud** [comment]
Closing as a duplicate
