### ISSUE TITLE
🐛 Docs - Page showing content as Markdown

### ISSUE THREAD

**Issue by tiagov8** [tinacms/tina.io#2034]
### 🐛 Describe the Bug

The content in this page is not rendering properly, showing raw Markdown:

https://tina.io/docs/self-hosted/existing-site/

### 💼 Tasks

- [x] 1. Investigate and fix

![Image](https://github.com/user-attachments/assets/14bad205-63b4-4070-9141-500c2b9eb37a)

cc @adamcogan

**Comment by joshbermanssw** [comment]
Fixed

**Comment by joshbermanssw** [comment]
![Image](https://github.com/user-attachments/assets/a3391bb3-035f-4299-b1fe-e22c82a85899)

**Figure: Page now loads instead of showing as markdown**
