### ISSUE TITLE
🎥 Tina Customer Journey Update

### ISSUE THREAD

**Issue by joshbermanssw** [tinacms/tina.io#2051]
cc: @landonmaxwell @sethdaily @Jord-Gui 

As per our conversation with Adam during the TinaCMS/Cloud sprint review. Adam wants us to film an update video based off of Levi's Tina customer journey https://www.youtube.com/watch?v=uJde9cz24ww&t=1075s

**Comment by Marxoz** [comment]
![Image](https://github.com/user-attachments/assets/b70b5b0e-ca2e-4408-961b-ba75157d4d03)
