### ISSUE TITLE
💄 About Page Content Update – Redesign

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tina.io#2067]
### 🩸 Pain
Update /about page for Copenhagen.

### 💡 Suggested Solution
[Update /about page as per Betty's design.](https://www.figma.com/proto/Jyj0SszjfSBc6Minkl3g1l/Tina.io?node-id=997-2061&t=ALjsQFNagE8Xvmja-0&scaling=min-zoom&content-scaling=fixed&page-id=997%3A2060&starting-point-node-id=997%3A2061&show-proto-sidebar=1)

### 💼 Tasks 
- [x] Redesign as per the above.

**Comment by manideep1428** [comment]
any help required , I love to do that ?

**Comment by isaaclombardssw** [comment]
> any help required , I love to do that ?

Sorry I've just seen your comment there – I've already been tackling this one since we were conscious about it being done by a certain date.

Most of the design PBIs on here don't have the same pressure attached to them. 
Just check a message over if any of them interest you – or you can submit a PBI if you want to suggest a page/fix/feature :)

**Comment by isaaclombardssw** [comment]
This one's done.
