### ISSUE TITLE
💄 Mobile View | Trusted by

### ISSUE THREAD

**Issue by joshbermanssw** [tinacms/tina.io#2069]
### 🩸 Pain

Mobile view, too much spacing near the 'trusted by component

### 💡 Suggested Solution

reduce spacing and make consistent (see figure below)

### 💼 Tasks 

- [x] reduce spacing 
- [x] test pass with betty

### ✅ Acceptance Criteria 

- [x] test pass betty

### 📸 Screenshots 

Cc: 

![Image](https://github.com/user-attachments/assets/a0e4338e-e616-4716-ad72-a04de7feaa3b)

**Comment by bettybondoc** [comment]
@joshbermanssw 

The spacing change affected desktop. It should only affect mobile.

- [ ] Please fix

**Comment by joshbermanssw** [comment]
Closing because this has been test passed however there seems to be a new bug with the component #2122
