### ISSUE TITLE
🐛 Error on Using Media with Digital Ocean Spaces

### ISSUE THREAD

**Issue by CDTdenisP** [tinacms/tina.io#2076]
Hello, trying to configure the media filesystem for Digital Ocean I found a _copy & paste_ error inside the example, you're using **pack. TinaCloudCloudinaryMediaStore.** I think should be **pack.TinaCloudDOSMediaStore**

```javascript
//tina/config.{ts,js}
//...

export default defineConfig({
  //...
  media: {
    loadCustomStore: async () => {
      const pack = await import('next-tinacms-dos')
      return pack.TinaCloudCloudinaryMediaStore // change to return pack.TinaCloudDOSMediaStore;
    },
  },
})`

**Comment by Jord-Gui** [comment]
Can confirm this is the case
![Image](https://github.com/user-attachments/assets/be8c4dfe-3210-47e7-b282-fd4de902accb)
**Figure: Setting up Digital Ocean Spaces in my Tina config**

**Comment by joshbermanssw** [comment]
Resolved, docs are updated ✅
