### ISSUE TITLE
♻  Refactor Blocks Folder

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tina.io#2077]
### Pain

The blocks folder contains more content than only blocks, and has been used for other miscellaneous bits of code. It could be better organized.

### Solution

Refactor the blocks folder, separating out non-block templates, UI code (ex. icon select) into distinct directories.

### Tasks

- [x] Sort and refactor.

**Comment by joshbermanssw** [comment]
in reference to `/contnent/blocks`

**Comment by joshbermanssw** [comment]
✅ Done - file structure has been fixed 

<img width="423" alt="Screenshot 2024-11-08 at 11 35 08 am" src="https://github.com/user-attachments/assets/0846296c-db38-4d3b-a307-55ee1fcb0a10">

_Update - sharedBlockFields is now sharedTemplates_
