### ISSUE TITLE
Events - which ones are done?

### ISSUE THREAD

**Issue by bradystroud** [tinacms/tina.io#2080]
cc @adamcogan @isaaclombardssw 

As per our conversation, its not clear what events are complete.

Options
- make it greyed out
- Add a green tick

![Image](https://github.com/user-attachments/assets/b3e09807-64a7-4b00-8256-a2405d3f601c)

**Comment by isaaclombardssw** [comment]
As per conversations with Adam and Brady, done differently, see https://github.com/tinacms/tina.io/pull/2081/files.

- [ ] Add a grey chip that says done next to completed events.

If the original suggested design is still wanted, this could be added as further work.
