### ISSUE TITLE
🔍 (CTF) Hueristic SEO Results – Improve SEO

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tina.io#2085]
### Pain

"GitHub-based CMS" and "Headless CMS" came up with no mention of Tina. 

It would be good to rank higher for some of these terms.

### Tasks

- [ ] Use Semrush to collect data on Tina.io SEO, then create PBIs to improve performance here.

**{This PBI was created in accordance with CTF on SEO Tools}**

**Comment by landonmaxwell** [comment]
Current status finding Tina with search "GitHub-based CMS":
- 3rd item on sponsored search (previously not listed)
- Top of page 3 for organic search results

![Image](https://github.com/user-attachments/assets/eeb069aa-9987-4c7f-802d-fc5c52174238)
Figure: TinaCMS sponsored results on Google
