### ISSUE TITLE
💄 Refactor + Redesign The IconPicker Component

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tina.io#2086]
As per chat with Brady...

### 🩸 Pain
Currently to use Josh's icon picker you have to import the target icons into the picker and your component using it.

The icon picker also uses the icon var name which may be confusing, and doesn't show the icon.

### 💡 Suggested Solution

See screenshots...

### 💼 Tasks 

- [ ] Update TinaCMS picker UI so the icon can be seen while selecting it.
- [x] Update TinaCMS picker UI so if named, the icons have a clearer name (i.e. no Fa prefix, etc.)

### 📸 Screenshots 

![Image](https://github.com/user-attachments/assets/566f1b7e-e474-49aa-bca3-4be2d0a938ab)
**From...**

![Image](https://github.com/user-attachments/assets/8f8b91ba-8fd8-4977-8d10-9ae963e9d91f)
**To...**

Cc:

**Comment by joshbermanssw** [comment]
Update as per PR

![Image](https://github.com/user-attachments/assets/f8fee7aa-f17d-44a0-a519-4bcde2ad4236)
![Image](https://github.com/user-attachments/assets/1d1b7aef-7c33-4166-a0b5-f7f48380df0e)

**Comment by isaaclombardssw** [comment]
Killed it 💯

**Comment by joshbermanssw** [comment]
Live✅ with a little help from Brady's design skills :)
