### ISSUE TITLE
About Page - Banner looks like it is end of the page (footer)

### ISSUE THREAD

**Issue by Marxoz** [tinacms/tina.io#2092]
The Orange banner between the 2 sections on the tina.io/about page looks like it is the end of the page when viewing the first section. 

It is probably because the banner runs across the screen. The same with the Unity one on tina.io.

![Image](https://github.com/user-attachments/assets/e77f1f4f-15ca-4cae-8eb7-dc526e86f036)
Figure: Banner on tina.io/about

![Image](https://github.com/user-attachments/assets/5cc6e356-fa32-4b0b-8106-ac7b3327456f)
Figure: Unity banner on tina.io

**Comment by Marxoz** [comment]
As per my conversation with @adamcogan, we are happy to update the colour of the 2 banners (and any others) to Seafoam.

See https://www.figma.com/proto/Jyj0SszjfSBc6Minkl3g1l/Tina.io?node-id=1192-3197&t=8UonKKaYdSdBmy9o-1&scaling=scale-down-width&content-scaling=fixed&page-id=997%3A2060&starting-point-node-id=1192%3A3197

**Comment by bettybondoc** [comment]
Hi @isaaclombardssw
cc @Marxoz 

Specs for this seafoam banner:
Gradient — teal-100 (#ccfbf1) to cyan-100 (#cffafe)
Transparency — 60



![Image](https://github.com/user-attachments/assets/684d3f59-f1a7-4354-98e9-3dfa1760abe7)

**Comment by isaaclombardssw** [comment]
Done – see https://github.com/tinacms/tina.io/pull/2094.
