### ISSUE TITLE
About Page - Add a link under the resources menu

### ISSUE THREAD

**Issue by Marxoz** [tinacms/tina.io#2093]
The About page can only be reached with a direct link.

1. Please add an "About TinaCMS" link under the Resources menu on the tina.io website
2. Also move Roadmap and Support links
FROM:
   Resources
TO:
   Community, 
under Showcase

![Image](https://github.com/user-attachments/assets/5a6b8741-1f68-4a5c-b470-b46eb9470c56)
Figure: Where to add the About link on the Tina.io website

![Image](https://github.com/user-attachments/assets/14b6fddf-9919-46b6-b309-b2b228ee8ebd)
Figure: Move the Roadmap and Support links to the Community tab, under Showcase

**Comment by isaaclombardssw** [comment]
Done, see https://github.com/tinacms/tina.io/pull/2095.
