### ISSUE TITLE
💄 CSS - clickable links should use cursor:pointer

### ISSUE THREAD

**Issue by wicksipedia** [tinacms/tina.io#2112]
It's not clear that links are clickable - the cursor doesn't change

- [ ] change stylesheet so that hyperlinks implement `cursor: pointer`

cc: @adamcogan @Marxoz @tiagov8

**Comment by tiagov8** [comment]
Hi @wicksipedia 

I coudn't reproduce this... navigating through Tina.io on my Mac/Chrome shows the pointer cursor when hovering all links I tested

**Comment by wicksipedia** [comment]
Using Safari
blog header links are divs with refs -> not anchors
no pointer
footer links have no pointer



https://github.com/user-attachments/assets/0994a4bd-7077-4689-b474-491bd4866663

**Comment by joshbermanssw** [comment]
Done and live - changed the `DynamicLink` component
