### ISSUE TITLE
💸 Tech Debt – Hard Coded Strings

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tina.io#2113]
### Pain

Currently, hard coded strings are used to determine block types and generate block pages.

This isn't maintainable as refactors on blocks require manually updating the types and knowledge of Tina is needed to construct the type-names by hand.

The offending file is `components/blocks/Blocks.tsx`.

A similar usage is can also be seen in the MediaComponent block.

Brady suggested we change this one 🔥.

### Tasks

- [ ] Investigate alternative approach.
- [ ] Change implementation.

**Comment by Marxoz** [comment]
Need to check this, but don't think it is possible.

@bradystroud Do you have any ideas?

**Comment by joshbermanssw** [comment]
> Need to check this, but don't think it is possible.
> 
> [@bradystroud](https://github.com/bradystroud) Do you have any ideas?

Spoke to the French guys using Tina and they also do it the same way as us - not sure it is possible

**Comment by isaaclombardssw** [comment]
I'm closing this issue.
