### ISSUE TITLE
📝 `Tina Cloud` to `TinaCloud` – Change Across Site

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tina.io#2114]
### Pain

We've rebranded Tina Cloud to TinaCloud (one word) but this isn't reflected across the site (see below).
I would love to do a blanket find and replace but may break things.

### Tasks

- [x] Change `Tina Cloud` to `TinaCloud` across the entire site, safely.

 
![Image](https://github.com/user-attachments/assets/0f1abe76-4969-4da7-997d-c0b8d5aae5c2)

**Comment by joshbermanssw** [comment]
Done nad Live✅
