### ISSUE TITLE
🐛 Logo Grid | Header Spacing change

### ISSUE THREAD

**Issue by joshbermanssw** [tinacms/tina.io#2122]
To reproduce go to home page and look at the logo grid header. After a few seconds it should change. see video 

**Tasks:**
- [ ] Investigate
- [ ] Fix 

**Acceptance Criteria**
- [ ] Test pass from Betty

https://github.com/user-attachments/assets/965554db-6405-4f59-bdfa-6ed388c1bce4

**Comment by isaaclombardssw** [comment]
I'm not experiencing this issue on Firefox / Intel Mac.

**Comment by joshbermanssw** [comment]
Unable to reproduce on Arc / Intel Mac

**Comment by joshbermanssw** [comment]
@sethdaily unable to produce on Edge / Windows
