### ISSUE TITLE
Icon Selector - allow no icon to be selected

### ISSUE THREAD

**Issue by bradystroud** [tinacms/tina.io#2138]
Really smooth UI. Should there be a way to deselect icons (i.e. none selected)?

If we don't want that, it's great.

_Originally posted by @isaaclombardssw in https://github.com/tinacms/tina.io/pull/2137#pullrequestreview-2276189180_

**Comment by joshbermanssw** [comment]
✅ Done and live 

![Image](https://github.com/user-attachments/assets/42cb5ba9-3f9f-461d-a6a3-200a75aae448)
