### ISSUE TITLE
🐛 Tina cloud - Some images are not found

### ISSUE THREAD

**Issue by EtayZaslavsky** [tinacms/tina.io#2159]
Uploaded images reside on public/upload in my nextjs+tina project.
On localhost they show correctly, however on tina cloud they don't (returns 404).
Found out that instead of residing here https://assets.tina.io/UUID/IMAGE-FILE.JPG, they are found here https://assets.tina.io/UUID/public/uploads/IMAGE-FILE.JPG 
any suggestions?

and btw, tina is awesome!
thank you for a great product. really liked the way you make developing so fun and simple.

**Comment by isaaclombardssw** [comment]
Any more info on you issue? Might be a question for the guys working on the CMS or cloud (looks like the automation has landed your issue in the public tina website repo!)

**Comment by EtayZaslavsky** [comment]
Thanks!

**Comment by Marxoz** [comment]
Seems to be edge case, will need more information
