### ISSUE TITLE
🐛 Docs - Mal-formatting error with long back-ticks

### ISSUE THREAD

**Issue by joshbermanssw** [tinacms/tina.io#2174]
cc: @ncn-ssw 

**Bug**
On the tina.io docs at https://tina.io/docs/introduction/faq/#common-tinacloud-errors there is a formatting issue when we have long strings surrounded in back-ticks (to replicate a 'codeblock') 

**Tasks**
- [ ] Investigate
- [ ] Fix 

![Image](https://github.com/user-attachments/assets/163227f5-6013-4ad9-ac02-7706e6485fc3)

**Figure: Mal-formatting on tina.io docs**

**Comment by isaaclombardssw** [comment]
Done – this was a styling issue.
