### ISSUE TITLE
UX - Improve Whats New

### ISSUE THREAD

**Issue by bradystroud** [tinacms/tina.io#2216]
Could improve the UX with some styling change (darkening) of these on hover - see current UX below.

![2024-09-17_14-23-28](https://github.com/user-attachments/assets/5d4f78d5-d7ea-471b-9a0c-02e8a8fad4e7)

_Originally posted by @isaaclombardssw in https://github.com/tinacms/tina.io/pull/2199#pullrequestreview-2308226274_

**Comment by joshbermanssw** [comment]
✅ Done and live as apart of PR #2199
