### ISSUE TITLE
🐛 `www` subdomain - Certificate warning

### ISSUE THREAD

**Issue by bradystroud** [tinacms/tina.io#2228]
https://www.tina.io/ is showing an expired cert warning in the browser.

FYI you'll probably need a SysAdmin e.g. @leahy268 to help

- [ ] Investigate and fix 

![Image](https://github.com/user-attachments/assets/950e4995-4d32-4199-ac0f-ad685c04f7db)

**Figure: Scary warning**

**Comment by isaaclombardssw** [comment]
😞

**Comment by leahy268** [comment]
Sorted.
I just needed to add it to vercel as well and redirect so that it has a certificate.
![Image](https://github.com/user-attachments/assets/f56173b1-a06c-4781-a332-f8d0d3ede733)
**Figure: www.tina.io added to vercel with a redirect to tina.io **
