### ISSUE TITLE
Broken links on the website

### ISSUE THREAD

**Issue by Vultwo** [tinacms/tina.io#2231]
I have noticed quite a few broken links on the website.
This page for example https://pre-beta.tina.io/docs/plugins/toolbar-widgets/
It is has multiple links to github repo's that do not seem to exist anymore:
https://github.com/tinacms/tinacms/blob/master/packages/react-tinacms-github/src/toolbar-plugins/RepoInfoPlugin.tsx
Is the functionality described on the website still possible?
We can't seem to get it working using the documentation and all references to it are broken.

**Comment by isaaclombardssw** [comment]
Hey @Vultwo, appreciate you making that issue.

The functionality you're describing is from the pre-beta version only, it looks like you're looking at that docs version.

I've created a PBI #2234 for anyone who encounters the same pitfall.

**Comment by isaaclombardssw** [comment]
I'm closing this as those legacy versions of the site aren't maintained.
