### ISSUE TITLE
🍱  Homepage Logo Grid – Add more showcase items

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tina.io#2237]
## Pain

As I saw while doing PBI #2222, some of the internal links have a bad fragment (no corresponding showcase page item).

These should either link to the showcase page with no fragment, the logo website or to the showcase page with a fragment that exists.

## Tasks

For each logo in the logo grid...

- [ ] Test the link, if no showcase content block exists (showcase page – https://tina.io/showcase/) then create one

Note: if it doesn't make sense to create one, link to the company's website.

**Comment by landonmaxwell** [comment]
1. Check each logo links to an associated showcase

**Comment by landonmaxwell** [comment]
Showcase needed:
- SSW
- NDC
- City of London

**Comment by landonmaxwell** [comment]
Added links, formatting & fixes to logo grid & showcase page: https://github.com/tinacms/tina.io/pull/2338

**Comment by landonmaxwell** [comment]
Blocked - waiting for Cloudinary transfer w/ @joshbermanssw
