### ISSUE TITLE
💄  Docs | ToC – Long titles interfere with the highlights

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tina.io#2244]
### 🩸 Pain
Long titles overlap with the highlight. Looks like a bug.

### 💡 Suggested Solution
TBC – possibly one for the designer.

### 💼 Tasks 

- [x] Fix

### 📸 Screenshots 

![Image](https://github.com/user-attachments/assets/63cf43f9-7926-4ee0-a80b-88b2130c9bd1)

Cc:

**Comment by Marxoz** [comment]
![Image](https://github.com/user-attachments/assets/0a6fcd34-316f-492d-9a59-954a63cb0449)
Figure: Also happens when wrapping

**Comment by Marxoz** [comment]
Need to talk to a designer to see if there is a better solution. Otherwise just remove.

**Comment by Marxoz** [comment]
As per my conversation with @bettybondoc , there is no need for the lines as we already have the selected link **bold**

**Comment by joshbermanssw** [comment]
Fixed and live
