### ISSUE TITLE
🐛 Homepage Quotes – No hover effect for Sean...

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tina.io#2245]
### 🩸 Pain
All the other quote cards scale and brighten on hover. Not sean.

### 💡 Suggested Solution
Add the same effect to sean's card. What do we have against sean :(

### 💼 Tasks 
- [ ] Fix

### 📸 Screenshots 

![Image](https://github.com/user-attachments/assets/a0397a66-52d2-458d-8e79-1336ca36acbe)
**Hovering card with effect**

![Image](https://github.com/user-attachments/assets/1bfa9b6a-58e7-4e61-af88-46066db485e1)
**Hovering card 'sean' but no effect**

Cc:

**Comment by joshbermanssw** [comment]
https://github.com/user-attachments/assets/c9661be9-0fbe-4a81-8cfe-17317f6339e2

**Figure: Hovering works on production for seans card?**

**Comment by isaaclombardssw** [comment]
I'd completed this, meant to be closed – fixed as per #2334
