### ISSUE TITLE
📝 Docs | Object Type – Adding Further Examples

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tina.io#2253]
### Pain

The Tina Docs [object page](https://tina-iy4q0d7p6-tinacms.vercel.app/docs/reference/types/object/) has been flagged as one of the harder to understand pages.

It doesn't have practical usage examples (like reference does).

### Tasks

- [x] Add an example use case into the examples section.

@Ben0189

**Comment by Ben0189** [comment]
Hey @isaaclombardssw , if the pr is merged should we close this PBI and mark as done ?(not sure about DOD for Tina io but just a reminder we might lost track on this task, because this is not in the sprint )

**Comment by isaaclombardssw** [comment]
I'd done some related work on the object page (see linked PR) – but there still aren't many usage examples so this should still be done.

**Comment by joshbermanssw** [comment]
Done and live at https://tina.io/docs/reference/types/object
