### ISSUE TITLE
🎥 TinaCMS - Media Manager improvement videos

### ISSUE THREAD

**Issue by Jord-Gui** [tinacms/tina.io#2297]
There have been a few improvements made to the TinaCMS Media Manager which we need to advertise:

- Mobile UI support
- Uploading non-image files
- Infinite scroll
- Media search

Media search has not been implemented yet.

Mobile UI support video has been recorded and sent to Landon.

Record the remaining Promotional Videos for the Media Manager and send it to Landon:
- [x] Being able to upload non-image files via the media manager
- [x] Infinite scroll

**Comment by Jord-Gui** [comment]
As per my conversation with @adamcogan, @leahy268, @landonmaxwell, the mobile UI support Done Video will be going public on its own. 

The next promotional video will just feature:
- Uploading non-image files
- Infinite scroll

**Comment by Jord-Gui** [comment]
I've recorded a v1 and sent to @landonmaxwell: https://www.youtube.com/watch?v=kKBt5H4xxyc

**Comment by landonmaxwell** [comment]
**New Dynamic Responsive UI - Use TinaCMS on your mobile devices 🤳 with Jord Gui** - https://youtu.be/a5h68j4JNkY
