### ISSUE TITLE
Tina.io Docs Examples on the Tina GQL Playground Vercel app

### ISSUE THREAD

**Issue by makingthingswork** [tinacms/tina.io#2317]
All example links seem to be broken. It wont load at all and I can see an error. Thanks
Example: https://tina-gql-playground.vercel.app/reference

```
Schema Compilation Error
Unexpected token '<', "<!DOCTYPE "... is not valid JSON
```
![Image](https://github.com/user-attachments/assets/0af21dd0-7b6e-431f-8029-4c6cb16b4bf5)

**Comment by isaaclombardssw** [comment]
Please see #2319 and add a comment if you'd like us to keep supporting this feature.

Currently we're looking into replacements (such as #2320), since the feature was using a lot of really old Tina packages (which is tricky to maintain and extend).

Cheers :)

**Comment by Marxoz** [comment]
These playgrounds have been removed completely
