### ISSUE TITLE
🖼️ Broken image link - Migrating from Forestry Docs

### ISSUE THREAD

**Issue by landonmaxwell** [tinacms/tina.io#2383]
Issue:
An image is missing.

1. Please fix

Comparing Tina & Forestry: Migrating from Forestry: Media | TinaCMS Docs

[https://tina.io/docs/forestry/media/](https://www.semrush.com/siteaudit/campaign/21323362/review/pagereport/page/6721aaa7a374c4234f4f26bd)

Missing asset: https://assets.tina.io/06bcd49e-f919-4e53-a2c4-77f656491c7dhttps://tina.io/img/media-manager-ui.png

![Image](https://github.com/user-attachments/assets/1250b776-1c4e-4f58-a5bc-069220538489)

**Comment by joshbermanssw** [comment]
Fixed and live
