### ISSUE TITLE
📝 Guide: How to migrate from Wordpress to TinaCMS

### ISSUE THREAD

**Issue by Marxoz** [tinacms/tina.io#2386]
Write a guide on migrating from Wordpress to TinaCMS
https://tina.io/docs/guides/

**Comment by isaaclombardssw** [comment]
As Lewis has moved to YakShaver – this is now back to the Tina.io domain.

Most of the work is done, see PR #2411.

It might just need some refinement.

**Comment by Lewkans** [comment]
✅ Done - See https://tina.io/docs/guides/converting-wordpress-to-tina
