### ISSUE TITLE
🐛 Broken image + duplicated folder with same purpose

### ISSUE THREAD

**Issue by tiagov8** [tinacms/tina.io#2413]
cc @landonmaxwell 

### 🐛 Describe the Bug

@adamcogan found this broken image.
I believe caused by https://github.com/tinacms/tina.io/pull/2338/files 

I also noticed that the SSW Website image for the showcase is sitting alone in a folder:`showcase`. All others are in another folder: `tina-showcase`. 

### 🧑‍💻 Reproduction Steps

1. Go to https://tina.io/showcase#protocol-labs
2. See error
3. Go to https://github.com/tinacms/tina.io/tree/main/public/img/showcase and see the image alone

### 💼 Tasks

- [ ] 1. Fix Devolver broken image. It should point to https://github.com/tinacms/tina.io/blob/main/public/img/tina-showcase/devolver.png
- [ ] 2. Move [SSW website image](https://github.com/tinacms/tina.io/blob/main/public/img/showcase/ssw-website-screenshot.jpg) to the same folder as the other showcase images + fix the path so it doesn't break

![Image](https://github.com/user-attachments/assets/e6d36060-3e57-4ccf-8927-f08ff2c5b214)

**Figure: Broken image**

![Image](https://github.com/user-attachments/assets/cb7a82a3-ca49-430d-97d8-09b870a452da)

**Figure: 2 folders, 1 purpose**

**Comment by joshbermanssw** [comment]
Fixed and Live
