### ISSUE TITLE
🍱  Homepage Events Component – Update Events + Assets

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tina.io#2418]
### Pain

All the events we're talking about on the homepage are done – where to next!?

### Tasks

- [ ] Update the events component with future events :)

### Screenshots

![Image](https://github.com/user-attachments/assets/0b0f3415-9d87-4540-b616-3856baae9efc)

**Comment by landonmaxwell** [comment]
See PR: https://github.com/tinacms/tina.io/pull/2504
