### ISSUE TITLE
📝 Docs - Add WordPress to Tina image

### ISSUE THREAD

**Issue by Lewkans** [tinacms/tina.io#2459]
### 💫 Describe the Issue With the Current Docs

As per @adamcogan's suggestion from the Sprint Review, the [Guide to Migrate from WordPress to Tina](https://tina.io/docs/guides/converting-wordpress-to-tina) should have an image that describes WordPress to Tina (i.e. WordPress Logo to Tina Logo, or something more creative).

### 📝 Outline the Proposed Change

1. On  [Guide to Migrate from WordPress to Tina](https://tina.io/docs/guides/converting-wordpress-to-tina), add an image that shows WordPress migration to Tina

### 💼 Tasks

- [x] Get a designer to create image
- [x] Add it to the top of the guide

### 📸 Screenshots 

Cc:

**Comment by joshbermanssw** [comment]
Done and live
