### ISSUE TITLE
💄 SEO – Improvements (more clarity)

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tina.io#2467]
cc's: @adamcogan @landonmaxwell 

### 🩸 Pain
The SEO object's 'Title' and 'Description' fields should be prefixed by "Meta" so they're distinguishable from the regular Title/Description's that may be on the page.

Additionally, an image could be included to show that this is related to SEO (google logo etc.)

### 💡 Suggested Solution
Update the labels, add an image.

### 💼 Tasks 

- [x] Update the labels
- [x] Add an image within the SEO object

**Comment by joshbermanssw** [comment]
Doen and live
