### ISSUE TITLE
💄 Comparison Box – Images to use Image Type

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tina.io#2500]
### 🩸 Pain
Currently the template for the comparison box takes in a link: 

![Image](https://github.com/user-attachments/assets/a54d353c-1bee-4808-a85d-ee2201405c52)

Tina has a great image type we could be use instead.

### 💼 Tasks 

- [ ] Change to image and upload all the current logos.

**Comment by joshbermanssw** [comment]
Fixed and live
