### ISSUE TITLE
💄 Hyperlinks look like plain text and not clickable links

### ISSUE THREAD

**Issue by wicksipedia** [tinacms/tina.io#2506]
When navigating the docs, it's hard to tell what is a hyperlink as it looks like normal text until hovered

![Image](https://github.com/user-attachments/assets/d03cfe50-0da4-4824-b1d2-69c56a0c5280)
**Figure: these are hyperlinks but if I didn't hover them, I wouldn't know as they look like the rest of the text**

- [ ] As per https://www.ssw.com.au/rules/underlined-links/ at minimum the links should have an underline

**Comment by joshbermanssw** [comment]
Fixed and Live
