### ISSUE TITLE
💄 Highlight Recommended Pricing Tier in Comparison Table

### ISSUE THREAD

**Issue by bettybondoc** [tinacms/tina.io#2543]
### 🩸 Pain
As per Adam's feedback during the Sprint Review, the recommended pricing tier in the table is not visually distinct, making it harder for users to identify

### 💡 Suggested Solution
Add a visual cue to highlight the recommended pricing tier in the table, improving clarity and guiding user decision-making

### 💼 Tasks 
- [x] Designer to propose a visual design for the highlight
- [x] Developer to implement the design in the pricing table

### ✅ Acceptance Criteria 
1. The recommended pricing tier is visually distinct in the table
2. The design is aligned with the overall style of the website
3. The implementation is responsive and works across all devices

### 📸 Screenshots 
![Image](https://github.com/user-attachments/assets/13a3a7a5-68f0-444b-8d42-fd0bb489346b)
**Figure: Pricing Table**

Cc: @landonmaxwell @joshbermanssw @adamcogan @Marxoz @isaaclombardssw

**Comment by joshbermanssw** [comment]
![Image](https://github.com/user-attachments/assets/8db2d181-0e91-4f1c-b9e0-2b446f5c1afd)

**Figure: Updated Highlighting**

- Also make some smaller UI fixes
