### ISSUE TITLE
✨ Tailwind Config Change - Colors

### ISSUE THREAD

**Issue by joshbermanssw** [tinacms/tina.io#2574]
The current tailwind config does not align with our designers designs 

**Tasks**
- [x] Get updated tailwind config file from @bettybondoc 
- [x] change file 
- [x] test

**Acceptance Criteria**
- [ ] Test with Betty

**Comment by bettybondoc** [comment]
@joshbermanssw
cc @Marxoz @landonmaxwell @isaaclombardssw 

## Updated colors based on the new Design Library:

```
colors: {
  seafoam: {
    50: '#EEFDF9',
    100: '#E9FBF4',
    150: '#C1F5EB', // Deprecated: This color will be removed in future designs.
    200: '#CFF5E6',
    300: '#B4EFD9',
    400: '#99E9CB',
    500: '#93E9BE',
    600: '#72C39B',
    700: '#529C7B',
    800: '#39745C',
    900: '#214C3D',
    950: '#122A21',
  },
  blue: {
    50: '#DCEEFF',
    100: '#B4DBFF',
    200: '#85C5FE',
    300: '#4EABFE',
    400: '#2296FE',
    500: '#0084FF',
    600: '#0574E4',
    700: '#0D5DBD',
    800: '#144696',
    900: '#1D2C6C',
    950: '#241748', // Newly added. Mirrors the value of 1000.
    1000: '#241748', // Deprecated: This color will be removed in future designs.
  },
  orange: {
    50: '#FFF8F3',
    100: '#FFEDE4',
    200: '#FFD3C1',
    300: '#FFAB8B',
    400: '#FF724B',
    500: '#EC4815',
    600: '#D13F13',
    700: '#A5310F',
    800: '#7A230B',
    900: '#4C1507',
    950: '#2F0D04',
  },
  success: '#22C55E',
  warning: '#F59E0B',
  error: '#EF4444',
},
```

## Changes to Colors
### Seafoam
- Updated color values:
  - **50**: Changed to `#EEFDF9` (was `#EEFCF7`).
  - **100**: Changed to `#E9FBF4` (was `#D7F9EE`).
  - **150**: Remains `#C1F5EB` but marked as deprecated with the comment:  
    `// Deprecated: This color will be removed in future designs.`
  - **200**: Changed to `#CFF5E6` (was `#A2F1E4`).
- Added new values for **300** through **950**.

### Blue
- Added **950** with the value `#241748` (mirrors **1000**).
- Marked **1000** as deprecated with the comment:  
  `// Deprecated: This color will be removed in future designs.`

### Gray
- Entire gray color palette was removed. We'll be using default Tailwind gray.

### Orange
- Updated the color scale for orange to ensure consistency within the same hue.
  - **50**: Added as `#FFF8F3`.
  - **100**: Changed to `#FFEDE4` (was `#F0C5AD`).
  - **200**: Changed to `#FFD3C1` (was `#EDA482`).
  - **300**: Changed to `#FFAB8B` (was `#EB8860`).
  - **400**: Changed to `#FF724B` (was `#EA6D43`).
  - **500**: Remains `#EC4815`.
  - **600**: Changed to `#D13F13` (was `#D94217`).
  - **700**: Changed to `#A5310F` (was `#C23414`).
  - **800**: Changed to `#7A230B` (was `#A91D04`).
  - **900**: Changed to `#4C1507` (was `#861103`).
  - **950**: Added as `#2F0D04`.

### Success and Warning
- **success**: Changed from `'green'` to `#3CAD3A`.
- **warning**: Changed from `'orange'` to `#ECAD15`.

**Comment by joshbermanssw** [comment]
Update - done and live, not tested with @bettybondoc as she's away for the next 2 weeks
