### ISSUE TITLE
✨ Search bar on smaller screens

### ISSUE THREAD

**Issue by joshbermanssw** [tinacms/tina.io#2575]
We dont have a search bar on the smaller screens for our docs search page (/search) 

Lets brainstorm how we can add this 

@bettybondoc @Marxoz

**Comment by bettybondoc** [comment]
Hi @joshbermanssw @Marxoz @landonmaxwell @adamcogan 

We could do something like this:
[Tina.io Docs Mobile](https://www.figma.com/proto/qFedRo7Xsc9oexI2IoPbFG/Tina.io-Design-Library?node-id=313-5554&node-type=frame&t=TGEWfNTyogp7ywDJ-0&scaling=min-zoom&content-scaling=fixed&page-id=313%3A5553&starting-point-node-id=313%3A5554&hide-ui=1)

Test passed by Jayden.

![Image](https://github.com/user-attachments/assets/2d07ff66-c0dd-4871-be05-469e27c9550e)
**Figure: Added the page heading, version, search and docs menu**

![Image](https://github.com/user-attachments/assets/d6c8c95d-97c7-4587-ba09-a751cc09f5aa)
**Figure: Table of Contents Overlay**

**Comment by joshbermanssw** [comment]
<img width="747" alt="Image" src="https://github.com/user-attachments/assets/e2cd3025-5369-4b39-9131-c42369a47881" />

**Figure: New Docs Rework w/ Searchbar**
