### ISSUE TITLE
🐛 Broken link on "docs/frameworks/next/app-router"

### ISSUE THREAD

**Issue by babakamyljanovssw** [tinacms/tina.io#2586]
### 🧑‍💻 Reproduction Steps

1. Go to ['Next JS | App Router'](https://tina.io/docs/frameworks/next/app-router) page
2. Find the link [Content Modeling with TinaCMS](https://tina.io/docs/frameworks/next/docs/extending-tina/overview/) and click the link
3. See 404 page

### 🎯 Expected Behaviour 

The link should navigate to proper documentation page or needs to be hidden/removed if the doc doesn't exist yet

### 💼 Tasks

- [x] Fix broken link

### ✅ Acceptance Criteria 

Broken link is fixed

### 📸 Screenshots 

https://tina.io/docs/frameworks/next/docs/extending-tina/overview
![Image](https://github.com/user-attachments/assets/59f98ac3-f624-4219-aae6-be2d682a2911)
**Figure: This link navigates to 404 page**

Cc: @landonmaxwell

**Comment by joshbermanssw** [comment]
Fixed and live
