### ISSUE TITLE
☄️ SEO - add meta editing for /blog & /events

### ISSUE THREAD

**Issue by landonmaxwell** [tinacms/tina.io#2616]
The /blog & /events pages don't have an option to update SEO (e.g. title or meta-description)

![Image](https://github.com/user-attachments/assets/52a67b2e-1fef-4eaf-8f5a-387ed4b760f3)
Figure: Blog page isn't editable on Tina

![Image](https://github.com/user-attachments/assets/c0c23a94-3fd7-482f-96f8-369ab04029b4)
Figure: Events post doesn't have the SEO edit block

**Comment by joshbermanssw** [comment]
✅ Done and live
