### ISSUE TITLE
Find place for our release notes

### ISSUE THREAD

**Issue by dwalkr** [tinacms/tina.io#989]
we removed release notes from the website because we are no longer publishing release notes to the same channel (github releases) that the website was fetching them from.

The first step here is going to be to determine how to publish release notes, and where (ideally to github releases again)

the next step will be to figure out how/where to put these on the website

**Comment by DirtyF** [comment]
On a related note, I can see us having a lighter versions/releases page à la https://reactjs.org/versions that points to the changelog on GitHub and only show the 10 latest releases for example.

Would be nice to also show the latest version published on the website that redirect to the releases page
<img width="1552" alt="tina-version-nav" src="https://user-images.githubusercontent.com/103008/128499525-1b6c0821-0878-41dd-8db1-7f8f6789e747.png">

**Comment by jamespohalloran** [comment]
@jeffsee55 Do I recall you doing some research on having these post to the Discord?

**Comment by jeffsee55** [comment]
I didn't really look into much, seems doable though
